### ISSUE TITLE
Can't have a `Spec` as a field in another model

### ISSUE THREAD

**Issue by callumforrester** [bluesky/scanspec#130]
As a user I would like to use `Spec` (and presumably `Region`) as a field in another pydantic model e.g.

```python
class Foo(BaseModel):
    spec: Spec
```

This produces the following error:

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vid18871/projects/bluesky/blueapi/venv/lib64/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 205, in __new__
    complete_model_class(
  File "/home/vid18871/projects/bluesky/blueapi/venv/lib64/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 534, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
  File "/home/vid18871/projects/bluesky/blueapi/venv/lib64/python3.10/site-packages/pydantic/main.py", line 643, in __get_pydantic_core_schema__
    return handler(source)
  File "/home/vid18871/projects/bluesky/blueapi/venv/lib64/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/home/vid18871/projects/bluesky/blueapi/venv/lib64/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 512, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/home/vid18871/projects/bluesky/blueapi/venv/lib64/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 784, in _generate_schema_inner
    return self._model_schema(obj)
  File "/home/vid18871/projects/bluesky/blueapi/venv/lib64/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 591, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/home/vid18871/projects/bluesky/blueapi/venv/lib64/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 591, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/home/vid18871/projects/bluesky/blueapi/venv/lib64/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 947, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "/home/vid18871/projects/bluesky/blueapi/venv/lib64/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1134, in _common_field_schema
    schema = self._apply_annotations(
  File "/home/vid18871/projects/bluesky/blueapi/venv/lib64/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1890, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/home/vid18871/projects/bluesky/blueapi/venv/lib64/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/home/vid18871/projects/bluesky/blueapi/venv/lib64/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1869, in inner_handler
    from_property = self._generate_schema_from_property(obj, source_type)
  File "/home/vid18871/projects/bluesky/blueapi/venv/lib64/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 679, in _generate_schema_from_property
    schema = get_schema(
  File "/home/vid18871/projects/bluesky/blueapi/venv/lib64/python3.10/site-packages/scanspec/core.py", line 234, in __get_pydantic_core_schema__
    return handler(source_type)
  File "/home/vid18871/projects/bluesky/blueapi/venv/lib64/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/home/vid18871/projects/bluesky/blueapi/venv/lib64/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 789, in _generate_schema_inner
    return self.match_type(obj)
  File "/home/vid18871/projects/bluesky/blueapi/venv/lib64/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 875, in match_type
    return self._unknown_type_schema(obj)
  File "/home/vid18871/projects/bluesky/blueapi/venv/lib64/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 415, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'scanspec.specs.Spec'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.8/u/schema-for-unknown-type
```

I also tried this, but got the same error:

```python
@discriminated_union_of_subclasses
class Foo(BaseModel):
    spec: Spec
```

**Comment by DiamondJoseph** [comment]
Can you try with @uses_tagged_union instead of @discriminated_union_of_subclasses ?

**Comment by callumforrester** [comment]
@DiamondJoseph same error
